### ISSUE TITLE
Possible to send "turn off" packet?

### ISSUE THREAD

**Issue by tonycassara** [jpoliv/wakeonlan#10]
Hi there,

Thanks for sharing this amazing tool. Is there a supported way to send "turn off" commands to a MAC address using this or any other tool that you know of?

Thank you,
Tony

**Comment by tonycassara** [comment]
Update to be more clear: I'm trying to send a "power off" command to my LG TV whenever my Mac goes to sleep. I might be able to achieve this with a Linux command but I'm struggling to find any documentation for this on LG's developer site.

**Comment by tonycassara** [comment]
Following up I realize now it is ridiculous to send a "turn off on lan" command as a security concern. I'll have to dive into the LG dev docs for my use case.

**Comment by elieteyssedou** [comment]
@tonycassara it is possible on windows using "ColorControl", I was able to turn off my LG C2 with it. (it uses wakeonlan for windows, not the same implementation as @jpoliv's wakeonlan)

But, actually I also would like to use wakeonlan to turn off my LG TV when my MAC goes to sleep, exact same usecase as you. Please tell me if you were able to do it somehow (hammerspoon?). 🙏🏻
