### ISSUE TITLE
Doesn't Work on Linux Mint 20

### ISSUE THREAD

**Issue by cjmoorejr** [jpoliv/wakeonlan#5]
After installation with Software Manager it will not Launch and can not be found in the Application list.

**Comment by brmib** [comment]
Same here. 
Is there any workaround to get it run?

**Comment by chrisnew** [comment]
it’s purely a cli tool, so you need to use it from your terminal

**Comment by jpoliv** [comment]
@cjmoorejr and @brmib As Christian already explained, wakeonlan is a command line tool intended to be executed from a terminal (or as a cronjob). A GUI was never planned.
